# Generated by Django 5.1.3 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nk_SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=50)),
                ('Select_branch', models.CharField(choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CIVIL', 'CIVIL'), ('MCA', 'MCA')], max_length=50)),
                ('College_name', models.CharField(max_length=30)),
                ('Select_current_year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=50)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_password', models.CharField(max_length=100)),
                ('Select_course_from_our_organization', models.CharField(choices=[('Python Programming', 'Python Programming'), ('Java Programming', 'Java Programming'), ('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('DevOps cum AWS', 'DevOps cum AWS'), ('Cyber Security', 'Cyber Security'), ('Communication', 'Communication'), ('Aptitude', 'Aptitude')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollement_id', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
