# Generated by Django 5.1.3 on 2025-04-29 06:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapil_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_id', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('course', models.CharField(choices=[('PYTHON', 'Python Programming'), ('JAVA', 'Java programming'), ('DATA_SCIENCE', 'Data Science'), ('DATA_ANALYTICS', 'Data Analytics'), ('DEVOPS', 'Devops cum AWS'), ('CYBEER_SECURITY', 'Cyber security'), ('COMMUNICATION', 'Communication'), ('APTITUDE', 'Aptitude')], max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('verification_reset_link', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('register_status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('password_changed_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(default='Manager', max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Non_kapil_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=100)),
                ('Branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Techonologhy'), ('ME', 'mechanical enf=gineering'), ('EE', 'Electical Engineering'), ('AE', 'Automobile Engineering'), ('DESIGN', 'Design and Architecture'), ('RE', 'Robotics Engineering')], max_length=100)),
                ('College_name', models.CharField(max_length=100)),
                ('Current_year', models.CharField(choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year')], max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_password', models.CharField(max_length=100)),
                ('Course', models.CharField(choices=[('PYTHON', 'Python Programming'), ('JAVA', 'Java Programming'), ('DATA_SCIENCE', 'Data Science'), ('DATA_ANALYTICS', 'Data Analytics'), ('DEVOPS', 'Devops cum AWS'), ('CYBER_SECURITY', 'Cyber Security'), ('COMMUNICATION', 'Communication'), ('Aptitude', 'Aptitude')], max_length=100)),
                ('Otp', models.CharField(blank=True, max_length=6, null=True)),
                ('Verification_reset_link', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('register_status', models.IntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('password_changed_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField()),
                ('number_of_mcq', models.IntegerField(default=0)),
                ('number_of_programs', models.IntegerField(default=0)),
                ('assessment_name', models.CharField(max_length=200, unique=True)),
                ('assessment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper_added_status', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='lmsapp.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(default='Trainer', max_length=50)),
                ('course', models.CharField(choices=[('Python Programming', 'Python Programming'), ('Java Programming', 'Java Programming'), ('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('DevOps cum AWS', 'DevOps cum AWS'), ('Cyber Security', 'Cyber Security'), ('Communication', 'Communication'), ('Aptitude', 'Aptitude')], max_length=50)),
                ('subjects', models.JSONField(default=list)),
                ('status', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='lmsapp.manager')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('assessment_duration', models.CharField(max_length=10)),
                ('questions', models.JSONField()),
                ('question_files', models.JSONField()),
                ('course_name', models.CharField(max_length=150)),
                ('assessment_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_paper', to='lmsapp.assessmentdetails')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_paper', to='lmsapp.manager')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_paper', to='lmsapp.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentdetails',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='lmsapp.trainer'),
        ),
    ]
