# Generated by Django 5.1.3 on 2025-04-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapil_student',
            name='manager',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lmsapp.manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kapil_student',
            name='trainer',
            field=models.JSONField(default=list),
        ),
    ]
