# Generated by Django 5.1.3 on 2025-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_kapil_student_manager_kapil_student_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapil_student',
            name='trainer_selected',
            field=models.BooleanField(default=False),
        ),
    ]
